### PR TITLE
Added Catalan

### PR DESCRIPTION
**Pull request by cibersheep**

### CODE REVIEW

**Review by NeoTheThird — COMMENTED** [review]
Not sure a prebuilt `.mo` is necessary. Will investigate.

**Comment by cibersheep** [comment]
Oh, you're right. Probably not if you have an automated way to add them into the app.
Soooooo feel free to delete it :)

**Comment by NeoTheThird** [comment]
I think it should be handled by /po/CMakeLists.txt, but i'm not sure yet. Thanks anyways ;)

**Comment by NeoTheThird** [comment]
There are some new strings, in case you're still interested in translating ;)

**Pull request merged**
